// <auto-generated />
using System;
using FCSP.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FCSP.Models.Migrations
{
    [DbContext(typeof(FcspDbContext))]
    partial class FcspDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FCSP.Models.Entities.BaseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BaseEntities");

                    b.HasDiscriminator().HasValue("BaseEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FCSP.Models.Entities.Criteria", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Criteria");
                });

            modelBuilder.Entity("FCSP.Models.Entities.CustomShoeDesign", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<long>("CustomShoeDesignTemplateId")
                        .HasColumnType("bigint");

                    b.Property<string>("DesignData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("DesignerMarkup")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<float>("TotalAmount")
                        .HasColumnType("real");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasIndex("CustomShoeDesignTemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("Status")
                                .HasColumnName("CustomShoeDesign_Status");
                        });

                    b.HasDiscriminator().HasValue("CustomShoeDesign");
                });

            modelBuilder.Entity("FCSP.Models.Entities.CustomShoeDesignTemplate", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("ThreeDFileUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("3DFileUrl");

                    b.Property<string>("TwoDImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("2DImageUrl");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasIndex("UserId");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("IsDeleted")
                                .HasColumnName("CustomShoeDesignTemplate_IsDeleted");

                            t.Property("Name")
                                .HasColumnName("CustomShoeDesignTemplate_Name");

                            t.Property("UserId")
                                .HasColumnName("CustomShoeDesignTemplate_UserId");
                        });

                    b.HasDiscriminator().HasValue("CustomShoeDesignTemplate");
                });

            modelBuilder.Entity("FCSP.Models.Entities.CustomShoeDesignTexture", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<long>("CustomShoeDesignId")
                        .HasColumnType("bigint");

                    b.Property<long>("TextureId")
                        .HasColumnType("bigint");

                    b.HasIndex("CustomShoeDesignId");

                    b.HasIndex("TextureId");

                    b.HasDiscriminator().HasValue("CustomShoeDesignTexture");
                });

            modelBuilder.Entity("FCSP.Models.Entities.CustomShoeDesignTextures", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<long>("CustomShoeDesignId")
                        .HasColumnType("bigint");

                    b.Property<long>("TextureId")
                        .HasColumnType("bigint");

                    b.HasIndex("CustomShoeDesignId");

                    b.HasIndex("TextureId");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("CustomShoeDesignId")
                                .HasColumnName("CustomShoeDesignTextures_CustomShoeDesignId");

                            t.Property("TextureId")
                                .HasColumnName("CustomShoeDesignTextures_TextureId");
                        });

                    b.HasDiscriminator().HasValue("CustomShoeDesignTextures");
                });

            modelBuilder.Entity("FCSP.Models.Entities.DesignPreview", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<long>("CustomShoeDesignId")
                        .HasColumnType("bigint");

                    b.Property<string>("PreviewImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CustomShoeDesignId");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("CustomShoeDesignId")
                                .HasColumnName("DesignPreview_CustomShoeDesignId");
                        });

                    b.HasDiscriminator().HasValue("DesignPreview");
                });

            modelBuilder.Entity("FCSP.Models.Entities.DesignService", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<long>("CustomShoeDesignId")
                        .HasColumnType("bigint");

                    b.Property<float?>("Price")
                        .HasColumnType("real");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ServiceId1")
                        .HasColumnType("bigint");

                    b.HasIndex("CustomShoeDesignId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ServiceId1");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("CustomShoeDesignId")
                                .HasColumnName("DesignService_CustomShoeDesignId");

                            t.Property("Price")
                                .HasColumnName("DesignService_Price");
                        });

                    b.HasDiscriminator().HasValue("DesignService");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Designer", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<float>("CommissionRate")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasIndex("UserId");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("Description")
                                .HasColumnName("Designer_Description");

                            t.Property("Status")
                                .HasColumnName("Designer_Status");

                            t.Property("UserId")
                                .HasColumnName("Designer_UserId");
                        });

                    b.HasDiscriminator().HasValue("Designer");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Manufacturer", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<float>("CommissionRate")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasIndex("UserId");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("CommissionRate")
                                .HasColumnName("Manufacturer_CommissionRate");

                            t.Property("Name")
                                .HasColumnName("Manufacturer_Name");

                            t.Property("Status")
                                .HasColumnName("Manufacturer_Status");

                            t.Property("UserId")
                                .HasColumnName("Manufacturer_UserId");
                        });

                    b.HasDiscriminator().HasValue("Manufacturer");
                });

            modelBuilder.Entity("FCSP.Models.Entities.ManufacturerCriteria", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<long>("CriteriaId")
                        .HasColumnType("bigint");

                    b.Property<long>("ManufacturerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasIndex("CriteriaId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("Status")
                                .HasColumnName("ManufacturerCriteria_Status");
                        });

                    b.HasDiscriminator().HasValue("ManufacturerCriteria");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Notification", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasIndex("UserId");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("IsDeleted")
                                .HasColumnName("Notification_IsDeleted");

                            t.Property("UserId")
                                .HasColumnName("Notification_UserId");
                        });

                    b.HasDiscriminator().HasValue("Notification");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Order", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<float>("AmountPaid")
                        .HasColumnType("real");

                    b.Property<long>("ShippingInfoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ShippingInfoId1")
                        .HasColumnType("bigint");

                    b.Property<int>("ShippingStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<float>("TotalPrice")
                        .HasColumnType("real");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("VoucherId")
                        .HasColumnType("bigint");

                    b.Property<long?>("VoucherId1")
                        .HasColumnType("bigint");

                    b.HasIndex("ShippingInfoId");

                    b.HasIndex("ShippingInfoId1");

                    b.HasIndex("UserId");

                    b.HasIndex("VoucherId");

                    b.HasIndex("VoucherId1");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("Status")
                                .HasColumnName("Order_Status");

                            t.Property("UserId")
                                .HasColumnName("Order_UserId");
                        });

                    b.HasDiscriminator().HasValue("Order");
                });

            modelBuilder.Entity("FCSP.Models.Entities.OrderDetail", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<long>("CustomShoeDesignId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasIndex("CustomShoeDesignId");

                    b.HasIndex("OrderId");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("CustomShoeDesignId")
                                .HasColumnName("OrderDetail_CustomShoeDesignId");

                            t.Property("Price")
                                .HasColumnName("OrderDetail_Price");
                        });

                    b.HasDiscriminator().HasValue("OrderDetail");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Payment", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.HasIndex("OrderId");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("OrderId")
                                .HasColumnName("Payment_OrderId");
                        });

                    b.HasDiscriminator().HasValue("Payment");
                });

            modelBuilder.Entity("FCSP.Models.Entities.PaymentGateway", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasIndex("UserId");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("PaymentMethod")
                                .HasColumnName("PaymentGateway_PaymentMethod");

                            t.Property("Status")
                                .HasColumnName("PaymentGateway_Status");

                            t.Property("UserId")
                                .HasColumnName("PaymentGateway_UserId");
                        });

                    b.HasDiscriminator().HasValue("PaymentGateway");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Posts", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasIndex("UserId");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("Content")
                                .HasColumnName("Posts_Content");

                            t.Property("IsDeleted")
                                .HasColumnName("Posts_IsDeleted");

                            t.Property("Title")
                                .HasColumnName("Posts_Title");

                            t.Property("UserId")
                                .HasColumnName("Posts_UserId");
                        });

                    b.HasDiscriminator().HasValue("Posts");
                });

            modelBuilder.Entity("FCSP.Models.Entities.PostsComments", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("PostsId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasIndex("PostsId");

                    b.HasIndex("UserId");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("IsDeleted")
                                .HasColumnName("PostsComments_IsDeleted");

                            t.Property("UserId")
                                .HasColumnName("PostsComments_UserId");
                        });

                    b.HasDiscriminator().HasValue("PostsComments");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Rating", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CustomShoeDesignId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("UserRating")
                        .HasColumnType("int");

                    b.HasIndex("CustomShoeDesignId");

                    b.HasIndex("UserId");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("Comment")
                                .HasColumnName("Rating_Comment");

                            t.Property("CustomShoeDesignId")
                                .HasColumnName("Rating_CustomShoeDesignId");

                            t.Property("IsDeleted")
                                .HasColumnName("Rating_IsDeleted");

                            t.Property("UserId")
                                .HasColumnName("Rating_UserId");
                        });

                    b.HasDiscriminator().HasValue("Rating");
                });

            modelBuilder.Entity("FCSP.Models.Entities.ReturnedCustomShoe", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<long>("CustomShoeDesignId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasIndex("CustomShoeDesignId");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("CustomShoeDesignId")
                                .HasColumnName("ReturnedCustomShoe_CustomShoeDesignId");

                            t.Property("IsDeleted")
                                .HasColumnName("ReturnedCustomShoe_IsDeleted");

                            t.Property("Price")
                                .HasColumnName("ReturnedCustomShoe_Price");
                        });

                    b.HasDiscriminator().HasValue("ReturnedCustomShoe");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Service", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("ManufacturerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("IsDeleted")
                                .HasColumnName("Service_IsDeleted");

                            t.Property("ManufacturerId")
                                .HasColumnName("Service_ManufacturerId");
                        });

                    b.HasDiscriminator().HasValue("Service");
                });

            modelBuilder.Entity("FCSP.Models.Entities.SetServiceAmount", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ServiceId1")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ServiceId1");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("Amount")
                                .HasColumnName("SetServiceAmount_Amount");

                            t.Property("ServiceId")
                                .HasColumnName("SetServiceAmount_ServiceId");

                            t.Property("ServiceId1")
                                .HasColumnName("SetServiceAmount_ServiceId1");

                            t.Property("Status")
                                .HasColumnName("SetServiceAmount_Status");
                        });

                    b.HasDiscriminator().HasValue("SetServiceAmount");
                });

            modelBuilder.Entity("FCSP.Models.Entities.ShippingInfo", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("UserId");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("IsDeleted")
                                .HasColumnName("ShippingInfo_IsDeleted");

                            t.Property("UserId")
                                .HasColumnName("ShippingInfo_UserId");
                        });

                    b.HasDiscriminator().HasValue("ShippingInfo");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Texture", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Prompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasIndex("UserId");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("IsDeleted")
                                .HasColumnName("Texture_IsDeleted");

                            t.Property("Status")
                                .HasColumnName("Texture_Status");

                            t.Property("UserId")
                                .HasColumnName("Texture_UserId");
                        });

                    b.HasDiscriminator().HasValue("Texture");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Transaction", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<long>("OrderDetailId")
                        .HasColumnType("bigint");

                    b.Property<long>("PaymentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReceiverId")
                        .HasColumnType("bigint");

                    b.HasIndex("OrderDetailId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("Amount")
                                .HasColumnName("Transaction_Amount");
                        });

                    b.HasDiscriminator().HasValue("Transaction");
                });

            modelBuilder.Entity("FCSP.Models.Entities.User", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<float?>("Balance")
                        .HasColumnType("real");

                    b.Property<long?>("DefaultAddressId")
                        .HasColumnType("bigint");

                    b.Property<string>("Dob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasIndex("DefaultAddressId");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("Gender")
                                .HasColumnName("User_Gender");

                            t.Property("IsDeleted")
                                .HasColumnName("User_IsDeleted");

                            t.Property("Name")
                                .HasColumnName("User_Name");
                        });

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("FCSP.Models.Entities.UserActivity", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ViewAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewDuration")
                        .HasColumnType("int");

                    b.Property<long>("ViewedDesignId")
                        .HasColumnType("bigint");

                    b.HasIndex("UserId");

                    b.HasIndex("ViewedDesignId");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("UserId")
                                .HasColumnName("UserActivity_UserId");
                        });

                    b.HasDiscriminator().HasValue("UserActivity");
                });

            modelBuilder.Entity("FCSP.Models.Entities.UserRecommendation", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<long>("RecommendDesignId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasIndex("RecommendDesignId");

                    b.HasIndex("UserId");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("UserId")
                                .HasColumnName("UserRecommendation_UserId");
                        });

                    b.HasDiscriminator().HasValue("UserRecommendation");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Voucher", b =>
                {
                    b.HasBaseType("FCSP.Models.Entities.BaseEntity");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VoucherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoucherValue")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("Description")
                                .HasColumnName("Voucher_Description");

                            t.Property("Status")
                                .HasColumnName("Voucher_Status");
                        });

                    b.HasDiscriminator().HasValue("Voucher");
                });

            modelBuilder.Entity("FCSP.Models.Entities.CustomShoeDesign", b =>
                {
                    b.HasOne("FCSP.Models.Entities.CustomShoeDesignTemplate", "CustomShoeDesignTemplate")
                        .WithMany("CustomShoeDesigns")
                        .HasForeignKey("CustomShoeDesignTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FCSP.Models.Entities.User", "User")
                        .WithMany("CustomShoeDesigns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomShoeDesignTemplate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FCSP.Models.Entities.CustomShoeDesignTemplate", b =>
                {
                    b.HasOne("FCSP.Models.Entities.User", "User")
                        .WithMany("Templates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("FCSP.Models.Entities.CustomShoeDesignTexture", b =>
                {
                    b.HasOne("FCSP.Models.Entities.CustomShoeDesign", "CustomShoeDesign")
                        .WithMany("CustomShoeDesignTextures")
                        .HasForeignKey("CustomShoeDesignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FCSP.Models.Entities.Texture", "Texture")
                        .WithMany("CustomShoeDesignTextures")
                        .HasForeignKey("TextureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomShoeDesign");

                    b.Navigation("Texture");
                });

            modelBuilder.Entity("FCSP.Models.Entities.CustomShoeDesignTextures", b =>
                {
                    b.HasOne("FCSP.Models.Entities.CustomShoeDesign", "CustomShoeDesign")
                        .WithMany()
                        .HasForeignKey("CustomShoeDesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FCSP.Models.Entities.Texture", "Texture")
                        .WithMany()
                        .HasForeignKey("TextureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomShoeDesign");

                    b.Navigation("Texture");
                });

            modelBuilder.Entity("FCSP.Models.Entities.DesignPreview", b =>
                {
                    b.HasOne("FCSP.Models.Entities.CustomShoeDesign", "CustomShoeDesign")
                        .WithMany("DesignPreviews")
                        .HasForeignKey("CustomShoeDesignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomShoeDesign");
                });

            modelBuilder.Entity("FCSP.Models.Entities.DesignService", b =>
                {
                    b.HasOne("FCSP.Models.Entities.CustomShoeDesign", "CustomShoeDesign")
                        .WithMany("DesignServices")
                        .HasForeignKey("CustomShoeDesignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FCSP.Models.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FCSP.Models.Entities.Service", null)
                        .WithMany("DesignServices")
                        .HasForeignKey("ServiceId1");

                    b.Navigation("CustomShoeDesign");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Designer", b =>
                {
                    b.HasOne("FCSP.Models.Entities.User", "User")
                        .WithMany("Designers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Manufacturer", b =>
                {
                    b.HasOne("FCSP.Models.Entities.User", "User")
                        .WithMany("Manufacturers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FCSP.Models.Entities.ManufacturerCriteria", b =>
                {
                    b.HasOne("FCSP.Models.Entities.Criteria", "Criteria")
                        .WithMany("ManufacturerCriterias")
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FCSP.Models.Entities.Manufacturer", "Manufacturer")
                        .WithMany("ManufacturerCriterias")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Criteria");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Notification", b =>
                {
                    b.HasOne("FCSP.Models.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Order", b =>
                {
                    b.HasOne("FCSP.Models.Entities.ShippingInfo", "ShippingInfo")
                        .WithMany()
                        .HasForeignKey("ShippingInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FCSP.Models.Entities.ShippingInfo", null)
                        .WithMany("Orders")
                        .HasForeignKey("ShippingInfoId1");

                    b.HasOne("FCSP.Models.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FCSP.Models.Entities.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FCSP.Models.Entities.Voucher", null)
                        .WithMany("Orders")
                        .HasForeignKey("VoucherId1");

                    b.Navigation("ShippingInfo");

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("FCSP.Models.Entities.OrderDetail", b =>
                {
                    b.HasOne("FCSP.Models.Entities.CustomShoeDesign", "CustomShoeDesign")
                        .WithMany("OrderDetails")
                        .HasForeignKey("CustomShoeDesignId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FCSP.Models.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomShoeDesign");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Payment", b =>
                {
                    b.HasOne("FCSP.Models.Entities.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FCSP.Models.Entities.PaymentGateway", b =>
                {
                    b.HasOne("FCSP.Models.Entities.User", "User")
                        .WithMany("PaymentGateways")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Posts", b =>
                {
                    b.HasOne("FCSP.Models.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FCSP.Models.Entities.PostsComments", b =>
                {
                    b.HasOne("FCSP.Models.Entities.Posts", "Posts")
                        .WithMany("PostsComments")
                        .HasForeignKey("PostsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FCSP.Models.Entities.User", "User")
                        .WithMany("PostsComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Posts");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Rating", b =>
                {
                    b.HasOne("FCSP.Models.Entities.CustomShoeDesign", "CustomShoeDesign")
                        .WithMany("Ratings")
                        .HasForeignKey("CustomShoeDesignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FCSP.Models.Entities.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomShoeDesign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FCSP.Models.Entities.ReturnedCustomShoe", b =>
                {
                    b.HasOne("FCSP.Models.Entities.CustomShoeDesign", "CustomShoeDesign")
                        .WithMany("ReturnedCustomShoes")
                        .HasForeignKey("CustomShoeDesignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomShoeDesign");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Service", b =>
                {
                    b.HasOne("FCSP.Models.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Services")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("FCSP.Models.Entities.SetServiceAmount", b =>
                {
                    b.HasOne("FCSP.Models.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FCSP.Models.Entities.Service", null)
                        .WithMany("SetServiceAmounts")
                        .HasForeignKey("ServiceId1");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("FCSP.Models.Entities.ShippingInfo", b =>
                {
                    b.HasOne("FCSP.Models.Entities.User", "User")
                        .WithMany("ShippingInfos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Texture", b =>
                {
                    b.HasOne("FCSP.Models.Entities.User", "User")
                        .WithMany("Textures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Transaction", b =>
                {
                    b.HasOne("FCSP.Models.Entities.OrderDetail", "OrderDetail")
                        .WithMany()
                        .HasForeignKey("OrderDetailId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FCSP.Models.Entities.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FCSP.Models.Entities.User", "Receiver")
                        .WithMany("ReceivedTransactions")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderDetail");

                    b.Navigation("Payment");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("FCSP.Models.Entities.User", b =>
                {
                    b.HasOne("FCSP.Models.Entities.ShippingInfo", "DefaultAddress")
                        .WithMany()
                        .HasForeignKey("DefaultAddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DefaultAddress");
                });

            modelBuilder.Entity("FCSP.Models.Entities.UserActivity", b =>
                {
                    b.HasOne("FCSP.Models.Entities.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FCSP.Models.Entities.CustomShoeDesign", "ViewedDesign")
                        .WithMany("ViewedActivities")
                        .HasForeignKey("ViewedDesignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("ViewedDesign");
                });

            modelBuilder.Entity("FCSP.Models.Entities.UserRecommendation", b =>
                {
                    b.HasOne("FCSP.Models.Entities.CustomShoeDesign", "RecommendDesign")
                        .WithMany("Recommendations")
                        .HasForeignKey("RecommendDesignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FCSP.Models.Entities.User", "User")
                        .WithMany("Recommendations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RecommendDesign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Criteria", b =>
                {
                    b.Navigation("ManufacturerCriterias");
                });

            modelBuilder.Entity("FCSP.Models.Entities.CustomShoeDesign", b =>
                {
                    b.Navigation("CustomShoeDesignTextures");

                    b.Navigation("DesignPreviews");

                    b.Navigation("DesignServices");

                    b.Navigation("OrderDetails");

                    b.Navigation("Ratings");

                    b.Navigation("Recommendations");

                    b.Navigation("ReturnedCustomShoes");

                    b.Navigation("ViewedActivities");
                });

            modelBuilder.Entity("FCSP.Models.Entities.CustomShoeDesignTemplate", b =>
                {
                    b.Navigation("CustomShoeDesigns");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Manufacturer", b =>
                {
                    b.Navigation("ManufacturerCriterias");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Posts", b =>
                {
                    b.Navigation("PostsComments");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Service", b =>
                {
                    b.Navigation("DesignServices");

                    b.Navigation("SetServiceAmounts");
                });

            modelBuilder.Entity("FCSP.Models.Entities.ShippingInfo", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Texture", b =>
                {
                    b.Navigation("CustomShoeDesignTextures");
                });

            modelBuilder.Entity("FCSP.Models.Entities.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("CustomShoeDesigns");

                    b.Navigation("Designers");

                    b.Navigation("Manufacturers");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("PaymentGateways");

                    b.Navigation("Posts");

                    b.Navigation("PostsComments");

                    b.Navigation("Ratings");

                    b.Navigation("ReceivedTransactions");

                    b.Navigation("Recommendations");

                    b.Navigation("ShippingInfos");

                    b.Navigation("Templates");

                    b.Navigation("Textures");
                });

            modelBuilder.Entity("FCSP.Models.Entities.Voucher", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
